default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: tokudome
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: switchship2_development

test:
  <<: *default
  database: switchship2_test

production:
  <<: *default
  database: switchship2_production
  url: <%= ENV['DATABASE_URL'] %>